image: barichello/godot-ci:3.2

stages:
  - export
  - deploy

variables:
  SV_EXPORT_NAME: NeonmentServer
  CL_EXPORT_NAME: NeonmentClient

before_script:
  - mkdir -v -p builds/linux
  - mkdir -v -p builds/windows
  - mkdir -v -p builds/mac

linux-server:
  when: manual
  stage: export
  script:
    - godot -v --export "Linux Server" ./builds/$SV_EXPORT_NAME.x86_64
  artifacts:
    name: $SV_EXPORT_NAME-$CI_JOB_NAME
    paths:
      - builds/linux

linux-client:
  stage: export
  script:
    - godot -v --export "Linux Client" ./builds/$CL_EXPORT_NAME.x86_64
  artifacts:
    name: $CL_EXPORT_NAME-$CI_JOB_NAME
    paths:
      - builds/linux

windows-server:
  when: manual
  stage: export
  script:
    - godot -v --export "Windows Server" ./builds/$SV_EXPORT_NAME.exe
  artifacts:
    name: $SV_EXPORT_NAME-$CI_JOB_NAME
    paths:
      - builds/windows

windows-client:
  stage: export
  script:
    - godot -v --export "Windows Client" ./builds/$CL_EXPORT_NAME.exe
  artifacts:
    name: $CL_EXPORT_NAME-$CI_JOB_NAME
    paths:
      - builds/windows

mac-server:
  when: manual
  stage: export
  script:
    - godot -v --export "Mac Server" ./builds/$SV_EXPORT_NAME.zip
  artifacts:
    name: $SV_EXPORT_NAME-$CI_JOB_NAME
    paths:
      - builds/mac

mac-client:
  stage: export
  script:
    - godot -v --export "Mac Client" ./builds/$CL_EXPORT_NAME.zip
  artifacts:
    name: $CL_EXPORT_NAME-$CI_JOB_NAME
    paths:
      - builds/mac
