image: barichello/godot-ci:3.2

stages:
  - export

variables:
  SV_EXPORT_NAME: NeonmentServer
  CL_EXPORT_NAME: NeonmentClient
  LINUX_DIR: builds/linux
  WINDOWS_DIR: builds/windows
  MAC_DIR: builds/mac

before_script:
  - mkdir -v -p $LINUX_DIR
  - mkdir -v -p $WINDOWS_DIR
  - mkdir -v -p $MAC_DIR

.client-template: &client-template
  stage: export
  artifacts:
    name: $CL_EXPORT_NAME-$CI_JOB_NAME
  rules:
    - changes:
      - /icon.{png, import}
      - /project.godot
      - /export_presets.cfg
      - /common
      - /client

.server-template: &server-template
  stage: export
  artifacts:
    name: $SV_EXPORT_NAME-$CI_JOB_NAME
  rules:
    - changes:
      - /icon.{png, import}
      - /project.godot
      - /export_presets.cfg
      - /common
      - /server

.linux: &linux
  artifacts:
    paths:
      - $LINUX_DIR

.windows: &windows
  artifacts:
    paths:
      - $WINDOWS_DIR

.mac: &mac
  artifacts:
    paths:
      - $MAC_DIR

linux-server:
  <<: *server-template
  <<: *linux
  script:
    - godot -v --export-debug "Linux Server" ./$LINUX_DIR/$SV_EXPORT_NAME.x86_64

linux-client:
  <<: *client-template
  <<: *linux
  script:
    - godot -v --export-debug "Linux Client" ./$LINUX_DIR/$CL_EXPORT_NAME.x86_64

windows-server:
  <<: *server-template
  <<: *windows
  script:
    - godot -v --export-debug "Windows Server" ./$WINDOWS_DIR/$SV_EXPORT_NAME.exe

windows-client:
  <<: *client-template
  <<: *windows
  script:
    - godot -v --export-debug "Windows Client" ./$WINDOWS_DIR/$CL_EXPORT_NAME.exe

mac-server:
  <<: *server-template
  <<: *mac
  script:
    - godot -v --export-debug "Mac Server" ./$MAC_DIR/$SV_EXPORT_NAME.zip

mac-client:
  <<: *client-template
  <<: *mac
  script:
    - godot -v --export-debug "Mac Client" ./$MAC_DIR/$CL_EXPORT_NAME.zip
